using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;

namespace PointCloud.Tests.EditMode
{
    /// <summary>
    /// Builds tiny PLY files byte by byte.
    ///
    /// Written in code rather than committed as binaries so every byte is visible and
    /// reviewable — when a parser test fails, the fixture is the first thing you need to
    /// read, and a checked-in blob tells you nothing. Files land in a temp directory so the
    /// real path-based load is exercised end to end.
    /// </summary>
    public static class PlyFixtures
    {
        public static string CreateTempDirectory()
        {
            var path = Path.Combine(Path.GetTempPath(), "pcviz_ply_" + Guid.NewGuid().ToString("N")[..8]);
            Directory.CreateDirectory(path);
            return path;
        }

        /// <summary>Four points forming a unit tetrahedron-ish spread, with known colours.</summary>
        public static readonly (double x, double y, double z, byte r, byte g, byte b)[] Points =
        {
            (0.0,  0.0,  0.0,   255, 0,   0),
            (1.5, -2.25, 3.125, 0,   255, 0),
            (-4.5, 8.0, -16.75, 0,   0,   255),
            (100.25, 0.5, -0.125, 128, 64, 32),
        };

        // --- ASCII ---------------------------------------------------------------

        public static string WriteAsciiXyzRgb(string directory, string name = "ascii_xyz_rgb.ply")
        {
            var builder = new StringBuilder();
            builder.Append("ply\n")
                   .Append("format ascii 1.0\n")
                   .Append("comment generated by PlyFixtures — this comment mentions end_header on purpose\n")
                   .Append($"element vertex {Points.Length}\n")
                   .Append("property float x\nproperty float y\nproperty float z\n")
                   .Append("property uchar red\nproperty uchar green\nproperty uchar blue\n")
                   .Append("end_header\n");

            foreach (var p in Points)
                builder.Append(Invariant(p.x)).Append(' ')
                       .Append(Invariant(p.y)).Append(' ')
                       .Append(Invariant(p.z)).Append(' ')
                       .Append(p.r).Append(' ').Append(p.g).Append(' ').Append(p.b).Append('\n');

            return Write(directory, name, Encoding.ASCII.GetBytes(builder.ToString()));
        }

        /// <summary>ASCII with CRLF line endings, which Windows exporters produce.</summary>
        public static string WriteAsciiCrLf(string directory, string name = "ascii_crlf.ply")
        {
            var builder = new StringBuilder();
            builder.Append("ply\r\n")
                   .Append("format ascii 1.0\r\n")
                   .Append($"element vertex {Points.Length}\r\n")
                   .Append("property float x\r\nproperty float y\r\nproperty float z\r\n")
                   .Append("end_header\r\n");

            foreach (var p in Points)
                builder.Append(Invariant(p.x)).Append(' ')
                       .Append(Invariant(p.y)).Append(' ')
                       .Append(Invariant(p.z)).Append("\r\n");

            return Write(directory, name, Encoding.ASCII.GetBytes(builder.ToString()));
        }

        /// <summary>Float colours in 0-1, which by convention are already linear.</summary>
        public static string WriteAsciiFloatColor(string directory, string name = "ascii_float_color.ply")
        {
            var builder = new StringBuilder();
            builder.Append("ply\nformat ascii 1.0\n")
                   .Append($"element vertex {Points.Length}\n")
                   .Append("property float x\nproperty float y\nproperty float z\n")
                   .Append("property float red\nproperty float green\nproperty float blue\n")
                   .Append("end_header\n");

            foreach (var p in Points)
                builder.Append(Invariant(p.x)).Append(' ')
                       .Append(Invariant(p.y)).Append(' ')
                       .Append(Invariant(p.z)).Append(' ')
                       .Append(Invariant(p.r / 255.0)).Append(' ')
                       .Append(Invariant(p.g / 255.0)).Append(' ')
                       .Append(Invariant(p.b / 255.0)).Append('\n');

            return Write(directory, name, Encoding.ASCII.GetBytes(builder.ToString()));
        }

        /// <summary>A CloudCompare-style export: scalar_ prefixes and an unrecognised field.</summary>
        public static string WriteAsciiWithScalars(string directory, string name = "ascii_scalars.ply")
        {
            var builder = new StringBuilder();
            builder.Append("ply\nformat ascii 1.0\n")
                   .Append($"element vertex {Points.Length}\n")
                   .Append("property float x\nproperty float y\nproperty float z\n")
                   .Append("property float scalar_intensity\n")
                   .Append("property int scalar_label\n")
                   .Append("property float scalar_C2C_absolute_distances\n")
                   .Append("end_header\n");

            for (int i = 0; i < Points.Length; i++)
            {
                var p = Points[i];
                builder.Append(Invariant(p.x)).Append(' ')
                       .Append(Invariant(p.y)).Append(' ')
                       .Append(Invariant(p.z)).Append(' ')
                       .Append(Invariant(0.25 * i)).Append(' ')
                       .Append(i * 3).Append(' ')
                       .Append(Invariant(-1.0 + i)).Append('\n');
            }

            return Write(directory, name, Encoding.ASCII.GetBytes(builder.ToString()));
        }

        // --- Binary --------------------------------------------------------------

        public static string WriteBinaryXyzRgb(string directory, bool bigEndian,
                                               string name = null)
        {
            name ??= bigEndian ? "binary_be_xyz_rgb.ply" : "binary_le_xyz_rgb.ply";

            var header = Header(bigEndian,
                $"element vertex {Points.Length}",
                "property float x", "property float y", "property float z",
                "property uchar red", "property uchar green", "property uchar blue");

            var body = new List<byte>();
            foreach (var p in Points)
            {
                AppendFloat(body, (float)p.x, bigEndian);
                AppendFloat(body, (float)p.y, bigEndian);
                AppendFloat(body, (float)p.z, bigEndian);
                body.Add(p.r); body.Add(p.g); body.Add(p.b);
            }

            return Write(directory, name, Concat(header, body));
        }

        /// <summary>Geo-referenced doubles at UTM magnitudes, where float32 loses half a metre.</summary>
        public static string WriteBinaryDoubleUtm(string directory, double3 origin,
                                                  string name = "binary_double_utm.ply")
        {
            var header = Header(bigEndian: false,
                $"element vertex {Points.Length}",
                "property double x", "property double y", "property double z");

            var body = new List<byte>();
            foreach (var p in Points)
            {
                AppendDouble(body, origin.x + p.x, false);
                AppendDouble(body, origin.y + p.y, false);
                AppendDouble(body, origin.z + p.z, false);
            }

            return Write(directory, name, Concat(header, body));
        }

        /// <summary>Vertices followed by a face element with a list property, as a mesh export would be.</summary>
        public static string WriteBinaryWithTrailingFaces(string directory,
                                                          string name = "binary_with_faces.ply")
        {
            var header = Header(bigEndian: false,
                $"element vertex {Points.Length}",
                "property float x", "property float y", "property float z",
                "element face 2",
                "property list uchar int vertex_indices");

            var body = new List<byte>();
            foreach (var p in Points)
            {
                AppendFloat(body, (float)p.x, false);
                AppendFloat(body, (float)p.y, false);
                AppendFloat(body, (float)p.z, false);
            }

            // Two triangles. Never read, but they must not confuse the vertex block sizing.
            foreach (var triangle in new[] { new[] { 0, 1, 2 }, new[] { 1, 2, 3 } })
            {
                body.Add(3);
                foreach (int index in triangle) AppendInt(body, index, false);
            }

            return Write(directory, name, Concat(header, body));
        }

        /// <summary>Binary vertex block deliberately cut short.</summary>
        public static string WriteTruncated(string directory, string name = "truncated.ply")
        {
            var header = Header(bigEndian: false,
                "element vertex 1000",
                "property float x", "property float y", "property float z");

            var body = new List<byte>();
            for (int i = 0; i < 10; i++)   // 10 points where 1000 were promised
            {
                AppendFloat(body, i, false);
                AppendFloat(body, i, false);
                AppendFloat(body, i, false);
            }

            return Write(directory, name, Concat(header, body));
        }

        public static string WriteGarbage(string directory, string name = "garbage.ply") =>
            Write(directory, name, Encoding.ASCII.GetBytes("this is definitely not a ply file\n\0\x01\x02"));

        public static string WriteNoEndHeader(string directory, string name = "no_end_header.ply") =>
            Write(directory, name, Encoding.ASCII.GetBytes(
                "ply\nformat ascii 1.0\nelement vertex 4\nproperty float x\n"));

        public static string WriteUnknownType(string directory, string name = "unknown_type.ply") =>
            Write(directory, name, Encoding.ASCII.GetBytes(
                "ply\nformat ascii 1.0\nelement vertex 1\nproperty quadruple x\nend_header\n0\n"));

        public static string WriteNoPositions(string directory, string name = "no_positions.ply") =>
            Write(directory, name, Encoding.ASCII.GetBytes(
                "ply\nformat ascii 1.0\nelement vertex 2\nproperty float intensity\nend_header\n0.5\n0.25\n"));

        /// <summary>Header promises more ASCII lines than the body contains.</summary>
        public static string WriteAsciiShortBody(string directory, string name = "ascii_short_body.ply") =>
            Write(directory, name, Encoding.ASCII.GetBytes(
                "ply\nformat ascii 1.0\nelement vertex 100\n" +
                "property float x\nproperty float y\nproperty float z\nend_header\n" +
                "0 0 0\n1 1 1\n"));

        // --- helpers -------------------------------------------------------------

        public struct double3
        {
            public double x, y, z;
            public double3(double x, double y, double z) { this.x = x; this.y = y; this.z = z; }
        }

        static byte[] Header(bool bigEndian, params string[] lines)
        {
            var builder = new StringBuilder();
            builder.Append("ply\n")
                   .Append(bigEndian ? "format binary_big_endian 1.0\n" : "format binary_little_endian 1.0\n");
            foreach (var line in lines) builder.Append(line).Append('\n');
            builder.Append("end_header\n");
            return Encoding.ASCII.GetBytes(builder.ToString());
        }

        static void AppendFloat(List<byte> target, float value, bool bigEndian) =>
            Append(target, BitConverter.GetBytes(value), bigEndian);

        static void AppendDouble(List<byte> target, double value, bool bigEndian) =>
            Append(target, BitConverter.GetBytes(value), bigEndian);

        static void AppendInt(List<byte> target, int value, bool bigEndian) =>
            Append(target, BitConverter.GetBytes(value), bigEndian);

        static void Append(List<byte> target, byte[] bytes, bool bigEndian)
        {
            // BitConverter follows the host, which is little-endian on every platform this
            // ships to; reverse explicitly for the big-endian fixtures.
            if (bigEndian) Array.Reverse(bytes);
            target.AddRange(bytes);
        }

        static byte[] Concat(byte[] header, List<byte> body)
        {
            var bytes = new byte[header.Length + body.Count];
            Buffer.BlockCopy(header, 0, bytes, 0, header.Length);
            body.CopyTo(bytes, header.Length);
            return bytes;
        }

        static string Write(string directory, string name, byte[] bytes)
        {
            var path = Path.Combine(directory, name);
            File.WriteAllBytes(path, bytes);
            return path;
        }

        static string Invariant(double value) => value.ToString("R", CultureInfo.InvariantCulture);
    }
}
